# -*- coding: utf-8 -*-
"""The merged initial dataset.

Assembled once from three sources and then frozen: the pre-migration
index.md / jp.md (snapshotted under data/legacy/), the ORCID public record
(0000-0002-7486-3146) and the Researchmap API (permalink `shinichinamba`).

Every row records where its facts came from in ``source``.  Where the sources
disagreed the resolution was confirmed with the site owner; see
migration_report.md for the full list.  Do not edit this file to change the
data -- after migration the authoritative copy is data/cv_master.xlsx.
"""

T, F = True, False

APPOINTMENTS = [
    dict(id="utokyo_assistant_professor",
         start_date="2023-10", end_date=None, ongoing=T,
         position_ja="助教", position_en="Assistant Professor",
         department_ja="大学院医学系研究科 遺伝情報学",
         department_en="Department of Genome Informatics, Graduate School of Medicine",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         location_ja="東京, 日本", location_en="Tokyo, Japan",
         appointment_type="primary", sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="EN page said Oct 2024; ORCID and the JA page agree on 2023-10.",
         source="orcid;jp.md", verified=T),
    dict(id="riken_invited_faculty",
         start_date="2023-11", end_date=None, ongoing=T,
         position_ja="客員研究員", position_en="Invited Faculty",
         department_ja="システム遺伝学研究チーム",
         department_en="Laboratory for Systems Genetics",
         institution_ja="理化学研究所 生命医科学研究センター",
         institution_en="RIKEN Center for Integrative Medical Sciences",
         location_ja="横浜, 日本", location_en="Yokohama, Japan",
         appointment_type="invited", sort_order=1,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="EN page said Nov 2024; ORCID says 2023-11-01.",
         source="orcid", verified=T),
    dict(id="osaka_invited_faculty",
         start_date="2023-10", end_date="2025-03", ongoing=F,
         position_ja="招へい教員", position_en="Invited Faculty",
         department_ja="大学院医学系研究科 遺伝統計学",
         department_en="Department of Statistical Genetics, Graduate School of Medicine",
         institution_ja="大阪大学", institution_en="The University of Osaka",
         location_ja="大阪, 日本", location_en="Osaka, Japan",
         appointment_type="invited", sort_order=2,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="EN page showed this as ongoing from Oct 2024; ORCID says "
              "2023-10-01 to 2025-03-31 (ended).",
         source="orcid", verified=T),
]

CLINICAL_TRAINING = [
    dict(id="jrc_junior_resident",
         start_date="2018-04", end_date="2020-03", ongoing=F,
         position_ja="初期研修医", position_en="Junior Resident",
         institution_ja="日本赤十字社医療センター",
         institution_en="Japan Red Cross Medical Center",
         department_ja=None, department_en=None,
         location_ja="東京, 日本", location_en="Tokyo, Japan",
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
]

EDUCATION = [
    dict(id="osaka_phd",
         start_date="2020-04", end_date="2023-09", ongoing=F,
         degree_ja="博士（医学）", degree_en="Ph.D. (Medicine)",
         field_ja="遺伝統計学", field_en="Statistical Genetics",
         department_ja="大学院医学系研究科 医学専攻",
         department_en="Division of Medicine, Graduate School of Medicine",
         institution_ja="大阪大学", institution_en="The University of Osaka",
         advisor_ja="岡田 随象", advisor_en="Yukinori Okada",
         location_ja="大阪, 日本", location_en="Osaka, Japan",
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;orcid;researchmap", verified=T),
    dict(id="utokyo_md",
         start_date="2012-04", end_date="2018-03", ongoing=F,
         degree_ja="医学士", degree_en="M.D.",
         field_ja=None, field_en=None,
         department_ja="医学部医学科（教養学部理科三類）",
         department_en="School of Medicine, Faculty of Medicine",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         advisor_ja=None, advisor_en=None,
         location_ja="東京, 日本", location_en="Tokyo, Japan",
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;orcid;researchmap", verified=T),
]

AWARDS = [
    dict(id="inoue_research_award_2026", award_date="2026-02-04",
         award_ja="井上研究奨励賞",
         award_en="Inoue Research Award for Young Scientists",
         organization_ja="井上科学振興財団",
         organization_en="Inoue Foundation for Science",
         description_ja=None, description_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
    dict(id="jshg_best_oral_2025", award_date="2025-12-19",
         award_ja="第70回大会 大会最優秀口演賞",
         award_en="Best Oral Presentation Award, 70th Annual Meeting",
         organization_ja="日本人類遺伝学会",
         organization_en="Japanese Society of Human Genetics",
         description_ja=None, description_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
    dict(id="eshg_travel_award_2024", award_date="2024-10",
         award_ja="2024年ヨーロッパ人類遺伝学会 Annual Meeting トラベルアワード",
         award_en="Travel Award, ESHG Annual Meeting 2024",
         organization_ja="日本人類遺伝学会",
         organization_en="Japanese Society of Human Genetics",
         description_ja=None, description_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="Not previously on the website; imported from Researchmap.",
         source="researchmap", verified=T),
    dict(id="osaka_phd_excellence_2024", award_date="2024-03",
         award_ja="博士課程優秀者",
         award_en="Outstanding Doctoral Student Award",
         organization_ja="大阪大学大学院医学系研究科",
         organization_en="Graduate School of Medicine, The University of Osaka",
         description_ja=None, description_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="Not previously on the website; imported from Researchmap.",
         source="researchmap", verified=T),
]

FELLOWSHIPS = [
    dict(id="takeda_phd_scholarship",
         start_date="2020-04", end_date="2023-09", ongoing=F,
         fellowship_ja="医学部博士課程奨学助成",
         fellowship_en="Scholarship Grant for Ph.D. Program in Medicine",
         organization_ja="武田科学振興財団",
         organization_en="Takeda Science Foundation",
         amount_jpy=None, show_amount_web=F,
         show_amount_cv_short=F, show_amount_cv_full=F,
         description_ja=None, description_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="End date confirmed as 2023-09 by the site owner; ORCID records "
              "2024-03 and should be corrected there.",
         source="jp.md", verified=T),
]

GRANTS = [
    dict(id="jsps_kakenhi_wakate_2026",
         start_date="2026-04", end_date="2028-03", ongoing=F,
         agency_ja="日本学術振興会",
         agency_en="Japan Society for the Promotion of Science (JSPS)",
         program_ja="科学研究費助成事業 若手研究",
         program_en="Grant-in-Aid for Early-Career Scientists",
         title_ja="深層学習によるヒト脂質代謝の遺伝的基盤全体像の解明",
         title_en="Deep learning-based elucidation of the genetic architecture "
                  "of human lipid metabolism",
         role="PI", grant_number="26K18279",
         amount_jpy=4550000, amount_type="total_project",
         url="https://kaken.nii.ac.jp/grant/KAKENHI-PROJECT-26K18279",
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="Not previously on the website; imported from Researchmap.",
         source="researchmap;orcid", verified=T),
    dict(id="amed_genome_drug_2025",
         start_date="2025-10", end_date="2028-03", ongoing=F,
         agency_ja="日本医療研究開発機構（AMED）",
         agency_en="Japan Agency for Medical Research and Development (AMED)",
         program_ja="ゲノム創薬基盤推進研究事業 若手課題",
         program_en="Genome-based Drug Discovery Program (Early-Career)",
         title_ja="遺伝子変異の機能性スペクトラム統一的解析と"
                  "次世代創薬連携による創薬シーズ導出",
         title_en="Establishment of drug candidates through integrative "
                  "analysis of the functional spectrum of genetic mutations "
                  "and interdisciplinary collaboration of next-generation "
                  "drug discovery fields",
         role="PI", grant_number=None,
         amount_jpy=None, amount_type="unknown", url=None,
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap;orcid", verified=T),
    dict(id="amed_grifin_2024",
         start_date="2024-07", end_date="2027-03", ongoing=F,
         agency_ja="日本医療研究開発機構（AMED）",
         agency_en="Japan Agency for Medical Research and Development (AMED)",
         program_ja="GRIFIN 若手課題", program_en="GRIFIN (Early-Career)",
         title_ja="遺伝子–環境相互作用の学術・オミクス横断による個別化医療の実装",
         title_en="A trans-disciplinary and trans-omics study of "
                  "gene–environment interactions towards genomics-driven "
                  "personalized medicine",
         role="PI", grant_number=None,
         amount_jpy=None, amount_type="unknown", url=None,
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap;orcid", verified=T),
    dict(id="jfae_cvic_2024",
         start_date="2024-06", end_date=None, ongoing=T,
         agency_ja="日本応用酵素協会",
         agency_en="Japan Foundation for Applied Enzymology",
         program_ja="Cardiovascular Innovative Conference に関する研究助成 (CVIC)",
         program_en="Grants related to Cardiovascular Innovative Conference",
         title_ja="心血管疾患の遺伝子–環境相互作用解明によるゲノム個別化医療と創薬",
         title_en="Genomics-driven personalized medicine and drug discovery by "
                  "elucidating gene–environment interactions for "
                  "cardiovascular diseases",
         role="PI", grant_number=None,
         amount_jpy=None, amount_type="unknown", url=None,
         sort_order=0, visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="No end date recorded in Researchmap or ORCID.",
         source="index.md;jp.md;researchmap;orcid", verified=T),
]

TEACHING = [
    dict(id="utokyo_intro_medicine_2026",
         start_date="2026-04", end_date=None, ongoing=T,
         course_ja="医学に接する", course_en="Introduction to Medicine Seminar",
         activity_type="seminar",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         school_ja="医学部", school_en="Faculty of Medicine",
         role_ja=None, role_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note="Not previously on the website; imported from Researchmap.",
         source="researchmap", verified=T),
    dict(id="utokyo_biochem_lecture_2025",
         start_date="2025-04", end_date=None, ongoing=T,
         course_ja="生化学講義", course_en="Biochemistry (Lecture)",
         activity_type="lecture",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         school_ja="医学部", school_en="Faculty of Medicine",
         role_ja=None, role_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
    dict(id="utokyo_advanced_genetic_informatics_2024",
         start_date="2024-04", end_date=None, ongoing=T,
         course_ja="遺伝情報学各論", course_en="Advanced Genetic Informatics",
         activity_type="lecture",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         school_ja="大学院医学系研究科", school_en="Graduate School of Medicine",
         role_ja=None, role_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
    dict(id="utokyo_biochem_lab_2023",
         start_date="2023-10", end_date=None, ongoing=T,
         course_ja="生化学実習", course_en="Biochemistry (Laboratory Course)",
         activity_type="laboratory",
         institution_ja="東京大学", institution_en="The University of Tokyo",
         school_ja="医学部", school_en="Faculty of Medicine",
         role_ja=None, role_en=None, sort_order=0,
         visible_web=T, visible_cv_short=T, visible_cv_full=T,
         note=None, source="index.md;jp.md;researchmap", verified=T),
]

MEMBERSHIPS = [
    dict(id="ashg", start_date="2020", end_date=None, ongoing=T,
         organization_ja="米国人類遺伝学会",
         organization_en="American Society of Human Genetics",
         membership_type_ja=None, membership_type_en=None, sort_order=0,
         visible_web=F, visible_cv_short=T, visible_cv_full=T,
         note="Join year from ORCID. Not shown on the website.",
         source="researchmap;orcid", verified=T),
    dict(id="jshg", start_date="2021", end_date=None, ongoing=T,
         organization_ja="日本人類遺伝学会",
         organization_en="Japanese Society of Human Genetics",
         membership_type_ja=None, membership_type_en=None, sort_order=0,
         visible_web=F, visible_cv_short=T, visible_cv_full=T,
         note="Join year from ORCID. Not shown on the website.",
         source="researchmap;orcid", verified=T),
    dict(id="jsbi", start_date="2021", end_date=None, ongoing=T,
         organization_ja="日本バイオインフォマティクス学会",
         organization_en="Japanese Society for Bioinformatics",
         membership_type_ja=None, membership_type_en=None, sort_order=0,
         visible_web=F, visible_cv_short=T, visible_cv_full=T,
         note="Join year from ORCID. Not shown on the website.",
         source="researchmap;orcid", verified=T),
    dict(id="jca", start_date="2017", end_date=None, ongoing=T,
         organization_ja="日本癌学会",
         organization_en="Japanese Cancer Association",
         membership_type_ja=None, membership_type_en=None, sort_order=0,
         visible_web=F, visible_cv_short=T, visible_cv_full=T,
         note="Join year from ORCID. Not shown on the website.",
         source="researchmap;orcid", verified=T),
]

# Sheets with no data in any source.  They are created with headers only so a
# row can be appended later and flow straight through the pipeline.
INVITED_TALKS: list[dict] = []
REVIEWING: list[dict] = []
COMMITTEES: list[dict] = []
PATENTS: list[dict] = []

DATA = {
    "appointments": APPOINTMENTS,
    "clinical_training": CLINICAL_TRAINING,
    "education": EDUCATION,
    "awards": AWARDS,
    "fellowships": FELLOWSHIPS,
    "grants": GRANTS,
    "teaching": TEACHING,
    "invited_talks": INVITED_TALKS,
    "reviewing": REVIEWING,
    "committees": COMMITTEES,
    "patents": PATENTS,
    "memberships": MEMBERSHIPS,
}
