"""YAML serialization for the generated _data files.

Two hazards are handled here.  First, PyYAML would fold long Japanese titles
across lines, and a folded scalar rejoins with a space -- wrong for CJK.
Second, an unquoted ``2024-10-15`` comes back from Ruby's Psych as a Date and
``2024`` as an Integer, which silently changes what Liquid renders; every
date-like string is therefore force-quoted.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

DATE_LIKE = re.compile(r"^\d{4}(-\d{2}(-\d{2})?)?$")


class QStr(str):
    """A string that must survive as a string on the Ruby side."""


def _repr_qstr(dumper, value):
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(value),
                                   style="'")


yaml.SafeDumper.add_representer(QStr, _repr_qstr)


def protect(value):
    """Recursively wrap date-like strings so YAML keeps them as strings."""
    if isinstance(value, QStr):
        return value
    if isinstance(value, str):
        return QStr(value) if DATE_LIKE.match(value) else value
    if isinstance(value, dict):
        return {k: protect(v) for k, v in value.items()}
    if isinstance(value, list):
        return [protect(v) for v in value]
    return value


def dump(data) -> str:
    return yaml.dump(protect(data), Dumper=yaml.SafeDumper,
                     allow_unicode=True, default_flow_style=False,
                     sort_keys=False, width=10 ** 6)


def write_yaml(path: Path, data, *, generated_by: str) -> bool:
    """Write only if the content changed.  Returns True when it did.

    Leaving unchanged files alone keeps `git status` quiet and keeps the
    wholesale `cp -R _site docs` deploy from producing phantom diffs.
    """
    text = (f"# GENERATED by {generated_by} — DO NOT EDIT.\n"
            f"# Edit data/ and run `make -C scripts all` instead.\n")
    text += dump(data)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)
    return True
